### PR TITLE
Add Vagranfile and add how-to launch caliopen stack on local vagrant

### PR DESCRIPTION
**Pull request by ptran32**
These changes allows user to deploy caliopen stack on his local machine with vagrant

### CODE REVIEW

**Comment by gdchamal** [comment]
Need to update documentation in main repository to point on this new method for a vagrant box

**Comment by ptran32** [comment]
Ack

**Comment by iamdey** [comment]
ok to merge @gdchamal ?

**Comment by gdchamal** [comment]
Yes

**Pull request merged**
